name: Auto Release on Push

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 确保 `gradlew` 可执行
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 3. 提取版本号（从 `mods.toml` 文件中读取）
      - name: Extract version from mods.toml
        id: extract_version
        run: |
          version=$(grep -E "^version=" src/main/resources/META-INF/mods.toml | cut -d'"' -f2)
          echo "Extracted version: $version"
          echo "VERSION=$version" >> $GITHUB_ENV

      # 4. 创建 Tag
      - name: Create Tag
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/QingMo-A/EconoeySystem.git "v${{ env.VERSION }}"
          echo "Created and pushed tag: v${{ env.VERSION }}"

      # 5. 创建 Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          body: |
            This is an automated release for version ${{ env.VERSION }}.
            Check the release notes for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. 构建项目
      - name: Build Project
        run: ./gradlew build

      # 7. 上传构建的文件
      - name: Upload Artifact to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
